### ISSUE TITLE
Safariでの閲覧時に「WORKS」セクションのカラムが崩壊する

### ISSUE THREAD

**Issue by Atsumi-Gakuto** [Atsumi-Gakuto/Portfolio#1]
## 不具合概要
Appleの[Safari](https://www.apple.com/jp/safari/)でポートフォリオページを閲覧すると、「WORKS」セクション内の記事のカラムが崩壊する。記事の途中で次のカラムに移動して、記事が真っ二つになる。

Safariであれば、MacでもiPadでも確認された。

![Safari閲覧時のカラム](https://github.com/user-attachments/assets/e0445441-fe4c-41ba-bfd0-9535d97382ef)

## 原因推定とその対策
該当箇所はCSSを用いてカラム実装している。

```css
#works {
    column-count: 2;
    column-gap: 10px;
    -webkit-column-count: 2;
    -webkit-column-gap: 10px;
    -moz-column-count: 2;
    -moz-column-gap:  10px;
}
```

本不具合に対処するためには、css又はjavascriptで別のアプローチをとった実装をしなければならないと考えられる。
